//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftApp.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.provider_material = new HashSet<provider_material>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string unit_name { get; set; }
        public string image { get; set; }
        public double price { get; set; }
        public string name { get; set; }
        public int min_count { get; set; }
        public bool is_storage { get; set; }
        public int count_in_pack { get; set; }
        public int count { get; set; }
    
        public virtual type_material type_material { get; set; }
        public virtual units units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_material> provider_material { get; set; }
        public virtual storage storage { get; set; }
    }
}
